MOCK_CATEGORIES = [
    {"code": "ENV", "name": "基础环境监控", "description": "温湿度、水浸、空气质量等环境监控"},
    {"code": "POWER", "name": "电力与能源管理", "description": "PUE、UPS、能耗与断电监控"},
    {"code": "HW", "name": "服务器与硬件监控", "description": "CPU、内存、磁盘、风扇等硬件监控"},
    {"code": "NET", "name": "网络与连接", "description": "流量、丢包、证书与连通性监控"},
    {"code": "APP", "name": "应用与服务", "description": "接口性能、日志、容器与中间件监控"},
    {"code": "SEC", "name": "安防与资产", "description": "门禁、视频、资产与登录审计"},
    {"code": "ALERT", "name": "告警与通知", "description": "告警收敛、升级、通知与自愈"},
    {"code": "OPS", "name": "运维与自动化", "description": "远程控制、巡检、固件管理"},
    {"code": "CAP", "name": "容量规划", "description": "U位、电力、存储与资源回收"},
]

MOCK_FEATURES = [
    {"code": "1.01", "name": "温湿度热力图", "description": "在机房布局图上叠加实时温度/湿度热力分布层。", "category_code": "ENV", "severity": "info", "unit": "°C/%", "latest_value": "23.5/45", "config": {"type": "heatmap"}},
    {"code": "1.02", "name": "机柜进出风口温差监控", "description": "监测机柜前后门温差，评估散热效率。", "category_code": "ENV", "severity": "info", "unit": "°C", "latest_value": "6", "config": {"deltaThreshold": 10}},
    {"code": "1.03", "name": "水浸检测告警", "description": "监测精密空调或管道周围的漏水情况。", "category_code": "ENV", "severity": "critical", "unit": "次", "latest_value": "0", "config": {"sensor": "leak"}},
    {"code": "1.04", "name": "烟雾与消防联动", "description": "接入烟感信号，触发告警时自动切换大屏至火警模式。", "category_code": "ENV", "severity": "critical", "unit": "次", "latest_value": "0", "config": {"mode": "fire"}},
    {"code": "1.05", "name": "空气质量监控", "description": "PM2.5/粉尘浓度监测，防止设备积灰短路。", "category_code": "ENV", "severity": "info", "unit": "μg/m³", "latest_value": "18", "config": {"pm25": 18}},
    {"code": "1.06", "name": "精密空调状态监控", "description": "监控压缩机、风机状态及回风温度。", "category_code": "ENV", "severity": "info", "unit": "状态", "latest_value": "OK", "config": {"compressor": "on"}},
    {"code": "1.07", "name": "机房噪声监测", "description": "监控机房分贝值，判断设备异常震动。", "category_code": "ENV", "severity": "info", "unit": "dB", "latest_value": "42", "config": {"unit": "dB"}},
    {"code": "1.08", "name": "气流组织分析", "description": "可视化冷热通道气流走向。", "category_code": "ENV", "severity": "info", "unit": "状态", "latest_value": "stable", "config": {"mode": "airflow"}},
    {"code": "2.01", "name": "实时 PUE 仪表盘", "description": "实时计算并展示 Power Usage Effectiveness (PUE) 值。", "category_code": "POWER", "severity": "info", "unit": "", "latest_value": "1.38", "config": {"target": 1.5}},
    {"code": "2.02", "name": "UPS 电池健康度", "description": "监控 UPS 电池内阻、剩余容量及预计运行时长。", "category_code": "POWER", "severity": "info", "unit": "%", "latest_value": "88", "config": {"unit": "%"}},
    {"code": "2.03", "name": "机柜级能耗排名", "description": "列出 Top 10 高能耗机柜/企业。", "category_code": "POWER", "severity": "info", "unit": "榜单", "latest_value": "Top10", "config": {"ranking": "cabinets"}},
    {"code": "2.04", "name": "异常掉电检测", "description": "监测市电/UPS 切换状态，断电瞬间触发最高级别告警。", "category_code": "POWER", "severity": "critical", "unit": "次", "latest_value": "0", "config": {"switch": "normal"}},
    {"code": "2.05", "name": "电压电流波形分析", "description": "监测电压暂降、浪涌等电能质量问题。", "category_code": "POWER", "severity": "warning", "unit": "状态", "latest_value": "stable", "config": {"waveform": "normal"}},
    {"code": "2.06", "name": "智能PDU端口控制", "description": "远程控制 PDU 单个插座的开关（需硬件支持）。", "category_code": "POWER", "severity": "info", "unit": "端口", "latest_value": "24", "config": {"ports": 24}},
    {"code": "2.07", "name": "能源成本计算器", "description": "根据实时电价计算每日/月电费成本。", "category_code": "POWER", "severity": "info", "unit": "¥", "latest_value": "3200", "config": {"currency": "CNY"}},
    {"code": "2.08", "name": "碳排放统计", "description": "将能耗换算为碳排放量，支持 ESG 报告。", "category_code": "POWER", "severity": "info", "unit": "tCO2", "latest_value": "1.2", "config": {"unit": "tCO2"}},
    {"code": "3.01", "name": "CPU 温度过热告警", "description": "核心温度超过阈值（如 85°C）即时告警。", "category_code": "HW", "severity": "warning", "unit": "°C", "latest_value": "62", "config": {"threshold": 85}},
    {"code": "3.02", "name": "内存泄漏检测", "description": "长期内存占用率趋势分析，预测 OOM 风险。", "category_code": "HW", "severity": "warning", "unit": "趋势", "latest_value": "trend", "config": {"window": "7d"}},
    {"code": "3.03", "name": "磁盘 SMART 健康预测", "description": "基于 SMART 数据预测硬盘故障寿命。", "category_code": "HW", "severity": "info", "unit": "%", "latest_value": "92", "config": {"unit": "%"}},
    {"code": "3.04", "name": "RAID 状态监控", "description": "监控 RAID 阵列降级、重建进度。", "category_code": "HW", "severity": "warning", "unit": "状态", "latest_value": "healthy", "config": {"level": "RAID5"}},
    {"code": "3.05", "name": "风扇转速异常", "description": "监控服务器风扇转速，预防散热失效。", "category_code": "HW", "severity": "warning", "unit": "RPM", "latest_value": "3400", "config": {"unit": "RPM"}},
    {"code": "3.06", "name": "僵尸进程监控", "description": "发现长期占用资源的僵尸或异常进程。", "category_code": "HW", "severity": "warning", "unit": "个", "latest_value": "0", "config": {"threshold": 5}},
    {"code": "3.07", "name": "GPU 利用率监控", "description": "针对 AI/计算节点，监控 GPU 显存和算力使用率。", "category_code": "HW", "severity": "info", "unit": "%", "latest_value": "45", "config": {"unit": "%"}},
    {"code": "3.08", "name": "硬件变更审计", "description": "自动记录 CPU/内存/硬盘的拔插变更记录。", "category_code": "HW", "severity": "info", "unit": "次", "latest_value": "0", "config": {"audit": "enabled"}},
    {"code": "4.01", "name": "核心交换机流量拓扑", "description": "动态展示核心网络链路的实时流量负载。", "category_code": "NET", "severity": "info", "unit": "状态", "latest_value": "stable", "config": {"topology": "core"}},
    {"code": "4.02", "name": "异常大流量告警", "description": "突发流量峰值检测（DDoS 疑似攻击）。", "category_code": "NET", "severity": "critical", "unit": "%", "latest_value": "0", "config": {"threshold": "80%"}},
    {"code": "4.03", "name": "端口丢包率监控", "description": "监控关键链路的 CRC 错误和丢包率。", "category_code": "NET", "severity": "warning", "unit": "%", "latest_value": "0.2", "config": {"unit": "%"}},
    {"code": "4.04", "name": "光模块收发光功率", "description": "监测光纤链路衰减，预防光模块故障。", "category_code": "NET", "severity": "warning", "unit": "dBm", "latest_value": "-2.5", "config": {"unit": "dBm"}},
    {"code": "4.05", "name": "关键业务 ping 延时", "description": "持续 ping 核心网关或外网 DNS，监控网络连通性。", "category_code": "NET", "severity": "warning", "unit": "ms", "latest_value": "8", "config": {"unit": "ms"}},
    {"code": "4.06", "name": "TCP 连接数监控", "description": "监控服务器 TIME_WAIT、ESTABLISHED 连接数趋势。", "category_code": "NET", "severity": "info", "unit": "条", "latest_value": "1200", "config": {"state": "ESTABLISHED"}},
    {"code": "4.07", "name": "DNS 解析耗时", "description": "监控内部 DNS 解析响应速度。", "category_code": "NET", "severity": "warning", "unit": "ms", "latest_value": "20", "config": {"unit": "ms"}},
    {"code": "4.08", "name": "证书过期提醒", "description": "自动扫描 SSL 证书有效期，提前 30 天告警。", "category_code": "NET", "severity": "warning", "unit": "天", "latest_value": "25", "config": {"unit": "days"}},
    {"code": "5.01", "name": "数据库慢查询分析", "description": "抓取 MySQL/PG 慢查询日志并排行。", "category_code": "APP", "severity": "warning", "unit": "s", "latest_value": "2.3", "config": {"unit": "s"}},
    {"code": "5.02", "name": "接口响应时间 (RT) 监控", "description": "关键 API 接口的 P95/P99 响应耗时。", "category_code": "APP", "severity": "warning", "unit": "ms", "latest_value": "450", "config": {"unit": "ms"}},
    {"code": "5.03", "name": "HTTP 状态码分布", "description": "监控 4xx/5xx 错误比例，超过阈值告警。", "category_code": "APP", "severity": "warning", "unit": "%", "latest_value": "1.2", "config": {"unit": "%"}},
    {"code": "5.04", "name": "日志关键词告警", "description": "实时分析日志文件，匹配 Error/Exception 关键字。", "category_code": "APP", "severity": "warning", "unit": "次", "latest_value": "0", "config": {"keywords": ["Error", "Exception"]}},
    {"code": "5.05", "name": "容器健康检查", "description": "Docker 容器存活状态、重启次数监控。", "category_code": "APP", "severity": "warning", "unit": "次", "latest_value": "0", "config": {"restart": 0}},
    {"code": "5.06", "name": "中间件积压监控", "description": "Redis 队列长度、Kafka 消息堆积量监控。", "category_code": "APP", "severity": "warning", "unit": "条", "latest_value": "120", "config": {"unit": "msg"}},
    {"code": "6.01", "name": "门禁非法闯入告警", "description": "非授权时间的机房开门记录告警。", "category_code": "SEC", "severity": "critical", "unit": "次", "latest_value": "0", "config": {"policy": "office-hours"}},
    {"code": "6.02", "name": "视频监控画中画", "description": "在机房 3D 视图中集成摄像头实时画面。", "category_code": "SEC", "severity": "info", "unit": "路", "latest_value": "4", "config": {"feeds": 4}},
    {"code": "6.03", "name": "资产位置漂移", "description": "配合 RFID，当资产离开指定机柜时告警。", "category_code": "SEC", "severity": "warning", "unit": "次", "latest_value": "0", "config": {"rfid": "enabled"}},
]
